### ISSUE TITLE
Griptape nodes fail to load

### ISSUE THREAD

**Issue by aliinct** [griptape-ai/ComfyUI-Griptape#112]
I just updated ALL Comfy UI and the griptape nodes no longer load. Everything had been working prior to the update.
The error reads is re;ated to

cannot import name 'QueryTool' from 'griptape.tools'

the complete traceback reads

Traceback (most recent call last):
  File "S:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "S:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape\__init__.py", line 14, in <module>
    from .nodes.agent.CreateAgent import CreateAgent
  File "S:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape\nodes\agent\CreateAgent.py", line 1, in <module>
    from .BaseAgent import BaseAgent
  File "S:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape\nodes\agent\BaseAgent.py", line 2, in <module>
    from griptape.tools import QueryTool, VectorStoreTool
ImportError: cannot import name 'QueryTool' from 'griptape.tools' (S:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\griptape\tools\__init__.py)

Cannot import S:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape module for custom nodes: cannot import name 'QueryTool' from 'griptape.tools' (S:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\griptape\tools\__init__.py)

**Comment by shhlife** [comment]
Can you try unloading and reloading the nodes? It sounds like griptape isn’t updating properly.

Let me know if this works!

**Comment by shhlife** [comment]
Awesome, thanks! 👍
