### ISSUE TITLE
Exception Message: OllamaEmbeddingDriver.init() missing 1 required keyword-only argument: 'model'

### ISSUE THREAD

**Issue by Hullabalo** [griptape-ai/ComfyUI-Griptape#128]
Hi Jason,
I'm currently using LM Studio and Ollama, both servers are working fine. I updated Griptape today and I'm encountering two issues, the first one with Ollama. Up until now, I wasn't using embedding, and I find it hard to believe that it's a new requirement? (But I could be wrong :))

To make sure the faults were not caused by my own tinkering, I downloaded and installed a fresh portable Comfy, added ltdrdata Manager and Griptape as custom nodes. Here are the logs in this configuration for this first error.
Thanks.

'''
# ComfyUI Error Report
## Error Details
- **Node Type:** Griptape Agent Config: Ollama Drivers
- **Exception Type:** TypeError
- **Exception Message:** OllamaEmbeddingDriver.__init__() missing 1 required keyword-only argument: 'model'
## Stack Trace
```
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape\nodes\config\gtUIOllamaDriversConfig.py", line 62, in create
    drivers_config_params["embedding_driver"] = OllamaEmbeddingDriver(
                                                ^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.2-50-g0bfc7cc
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 8589279232
  - **VRAM Free:** 7444889600
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-09-18 23:36:04,472 - root - INFO - Total VRAM 8191 MB, total RAM 32717 MB
2024-09-18 23:36:04,472 - root - INFO - pytorch version: 2.4.1+cu124
2024-09-18 23:36:04,472 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-18 23:36:04,473 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync
2024-09-18 23:36:05,318 - root - INFO - Using pytorch cross attention
2024-09-18 23:36:06,611 - root - INFO - [Prompt Server] web root: D:\ComfyUI_windows_portable\ComfyUI\web
2024-09-18 23:36:08,789 - root - INFO - 
Import times for custom nodes:
2024-09-18 23:36:08,790 - root - INFO -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-09-18 23:36:08,790 - root - INFO -    0.4 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-09-18 23:36:08,791 - root - INFO -    1.3 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape
2024-09-18 23:36:08,791 - root - INFO - 
2024-09-18 23:36:08,800 - root - INFO - Starting server

2024-09-18 23:36:08,801 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-09-18 23:43:20,046 - root - INFO - got prompt
2024-09-18 23:43:20,567 - root - ERROR - !!! Exception during processing !!! OllamaEmbeddingDriver.__init__() missing 1 required keyword-only argument: 'model'
2024-09-18 23:43:20,569 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape\nodes\config\gtUIOllamaDriversConfig.py", line 62, in create
    drivers_config_params["embedding_driver"] = OllamaEmbeddingDriver(
                                                ^^^^^^^^^^^^^^^^^^^^^^
TypeError: OllamaEmbeddingDriver.__init__() missing 1 required keyword-only argument: 'model'

2024-09-18 23:43:20,570 - root - INFO - Prompt executed in 0.52 seconds
2024-09-18 23:43:40,041 - root - INFO - got prompt
2024-09-18 23:43:40,300 - root - ERROR - !!! Exception during processing !!! OllamaEmbeddingDriver.__init__() missing 1 required keyword-only argument: 'model'
2024-09-18 23:43:40,301 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape\nodes\config\gtUIOllamaDriversConfig.py", line 62, in create
    drivers_config_params["embedding_driver"] = OllamaEmbeddingDriver(
                                                ^^^^^^^^^^^^^^^^^^^^^^
TypeError: OllamaEmbeddingDriver.__init__() missing 1 required keyword-only argument: 'model'

2024-09-18 23:43:40,302 - root - INFO - Prompt executed in 0.26 seconds
2024-09-18 23:45:00,369 - root - INFO - got prompt
2024-09-18 23:45:00,638 - root - ERROR - !!! Exception during processing !!! OllamaEmbeddingDriver.__init__() missing 1 required keyword-only argument: 'model'
2024-09-18 23:45:00,638 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape\nodes\config\gtUIOllamaDriversConfig.py", line 62, in create
    drivers_config_params["embedding_driver"] = OllamaEmbeddingDriver(
                                                ^^^^^^^^^^^^^^^^^^^^^^
TypeError: OllamaEmbeddingDriver.__init__() missing 1 required keyword-only argument: 'model'

2024-09-18 23:45:00,640 - root - INFO - Prompt executed in 0.27 seconds
2024-09-18 23:49:09,760 - root - INFO - got prompt
2024-09-18 23:49:10,020 - root - ERROR - !!! Exception during processing !!! OllamaEmbeddingDriver.__init__() missing 1 required keyword-only argument: 'model'
2024-09-18 23:49:10,021 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape\nodes\config\gtUIOllamaDriversConfig.py", line 62, in create
    drivers_config_params["embedding_driver"] = OllamaEmbeddingDriver(
                                                ^^^^^^^^^^^^^^^^^^^^^^
TypeError: OllamaEmbeddingDriver.__init__() missing 1 required keyword-only argument: 'model'

2024-09-18 23:49:10,023 - root - INFO - Prompt executed in 0.26 seconds
2024-09-18 23:51:34,310 - root - INFO - got prompt
2024-09-18 23:51:34,574 - root - ERROR - !!! Exception during processing !!! OllamaEmbeddingDriver.__init__() missing 1 required keyword-only argument: 'model'
2024-09-18 23:51:34,575 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape\nodes\config\gtUIOllamaDriversConfig.py", line 62, in create
    drivers_config_params["embedding_driver"] = OllamaEmbeddingDriver(
                                                ^^^^^^^^^^^^^^^^^^^^^^
TypeError: OllamaEmbeddingDriver.__init__() missing 1 required keyword-only argument: 'model'

2024-09-18 23:51:34,576 - root - INFO - Prompt executed in 0.26 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":7,"last_link_id":4,"nodes":[{"id":2,"type":"Griptape Prompt Driver: Ollama","pos":{"0":1482,"1":4939},"size":{"0":378,"1":250},"flags":{},"order":0,"mode":2,"inputs":[],"outputs":[{"name":"DRIVER","type":"PROMPT_DRIVER","links":[2],"shape":3,"slot_index":0}],"properties":{"Node name for S&R":"Griptape Prompt Driver: Ollama"},"widgets_values":["http://127.0.0.1","11434","dolphin-mistral:latest",10,0.1,2048,"fixed",true,-1]},{"id":4,"type":"Griptape Tool: Query","pos":{"0":2056,"1":4851},"size":{"0":252,"1":26},"flags":{},"order":3,"mode":2,"inputs":[{"name":"prompt_driver","type":"PROMPT_DRIVER","link":2}],"outputs":[{"name":"TOOL","type":"TOOL_LIST","links":null,"shape":3}],"properties":{"Node name for S&R":"Griptape Tool: Query"}},{"id":3,"type":"Griptape Agent Config: Expand","pos":{"0":2044,"1":5422},"size":{"0":418.1999816894531,"1":126},"flags":{},"order":4,"mode":2,"inputs":[{"name":"config","type":"CONFIG","link":1}],"outputs":[{"name":"PROMPT_DRIVER","type":"PROMPT_DRIVER","links":null,"shape":3},{"name":"IMAGE_GENERATION_DRIVER","type":"DRIVER","links":null,"shape":3},{"name":"EMBEDDING_DRIVER","type":"EMBEDDING_DRIVER","links":null,"shape":3},{"name":"VECTOR_STORE_DRIVER","type":"VECTOR_STORE_DRIVER","links":null,"shape":3},{"name":"TEXT_TO_SPEECH_DRIVER","type":"TEXT_TO_SPEECH_DRIVER","links":null,"shape":3},{"name":"AUDIO_TRANSCRIPTION_DRIVER","type":"AUDIO_TRANSCRIPTION_DRIVER","links":null,"shape":3}],"properties":{"Node name for S&R":"Griptape Agent Config: Expand"}},{"id":6,"type":"Griptape Display: Data as Text","pos":{"0":2571.361328125,"1":5054.43017578125},"size":[378,76],"flags":{},"order":6,"mode":0,"inputs":[{"name":"INPUT","type":"*","link":4}],"outputs":[{"name":"OUTPUT","type":"STRING","links":null,"shape":3}],"properties":{},"widgets_values":[""]},{"id":5,"type":"Griptape Create: Agent","pos":{"0":2057.608154296875,"1":5028.6865234375},"size":[400,200],"flags":{},"order":5,"mode":0,"inputs":[{"name":"agent","type":"AGENT","link":null},{"name":"config","type":"CONFIG","link":3},{"name":"tools","type":"TOOL_LIST","link":null},{"name":"rulesets","type":"RULESET","link":null},{"name":"input_string","type":"STRING","link":null,"widget":{"name":"input_string"}}],"outputs":[{"name":"OUTPUT","type":"STRING","links":[4],"shape":3,"slot_index":0},{"name":"AGENT","type":"AGENT","links":null,"shape":3}],"properties":{"Node name for S&R":"Griptape Create: Agent"},"widgets_values":["","who are you ?"]},{"id":7,"type":"Griptape Embedding Driver: Ollama","pos":{"0":1469,"1":4747},"size":{"0":415.8000183105469,"1":106},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"DRIVER","type":"EMBEDDING_DRIVER","links":null,"shape":3}],"properties":{"Node name for S&R":"Griptape Embedding Driver: Ollama"},"widgets_values":["http://127.0.0.1","11434",null]},{"id":1,"type":"Griptape Agent Config: Ollama Drivers","pos":{"0":1396,"1":5289},"size":{"0":466.1999816894531,"1":322},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"CONFIG","type":"CONFIG","links":[1,3],"shape":3,"slot_index":0}],"properties":{"Node name for S&R":"Griptape Agent Config: Ollama Drivers"},"widgets_values":["http://127.0.0.1","11434","Prompt Driver","llama3.1:latest",10,0.1,2048,"fixed",true,-1,"Embedding Driver",null]}],"links":[[1,1,0,3,0,"CONFIG"],[2,2,0,4,0,"PROMPT_DRIVER"],[3,1,0,5,1,"CONFIG"],[4,5,0,6,0,"*"]],"groups":[],"config":{},"extra":{"ds":{"scale":1.0152559799477143,"offset":[-760.3620398468538,-4661.168309888848]}},"version":0.4}
```

'''

**Comment by Hullabalo** [comment]
Ok, it's resolved. It was late, and it would have been better to check the code directly instead of opening an issue for this problem. Sorry ;)

 ...\custom_nodes\ComfyUI-Griptape\nodes\drivers\gtUIOllamaEmbeddingDriver.py
                  
```
In order for Griptape to create an embedding driver, an embedding model must be specified.
                    
If there are no embedding models available, you may need to pull one from the registry.

For example, open a terminal and run:

ollama pull nomic-embed-text

Once it's finished, refresh your browser and you should see it in the list of available models.
```

**Comment by shhlife** [comment]
No worries! glad it's resolved. :)
