### ISSUE TITLE
LM Studio - Connection error

### ISSUE THREAD

**Issue by Hullabalo** [griptape-ai/ComfyUI-Griptape#129]
I’m opening another issue regarding LMStudio (I’m able to communicate with the API from Comfy using a set of nodes other than Griptape). CORS is enabled. The embedding (nomic) is loaded and recognized by the lmstudio driver. Same configuration as yesterday (freshly installed ComfyUI, Griptape and Manager are the only custom nodes). 'Connection error' is returned in the client interface by Create : Agent node, no error message in the server logs. Here are the messages in the console and the workflow used. Thanks for your insights.

![Griptape-LMStudio](https://github.com/user-attachments/assets/1b4c6086-c0b4-49d2-85ae-f6e547a3e710)

```
got prompt
[09/19/24 14:34:57] INFO     PromptTask 46d4f1e694e94948b16402d019174293
                             Input: who are you ?
Retrying request to /chat/completions in 0.907231 seconds
Retrying request to /chat/completions in 1.804645 seconds
<RetryCallState 1525830454928: attempt #1; slept for 0.0; last result: failed (APIConnectionError Connection error.)>
[09/19/24 14:35:06] ERROR    PromptTask 46d4f1e694e94948b16402d019174293
                             Connection error.
                             Traceback (most recent call last):
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\httpx\_transports\default.py"
                             , line 72, in map_httpcore_exceptions
                                 yield
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\httpx\_transports\default.py"
                             , line 236, in handle_request
                                 resp = self._pool.handle_request(req)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\httpcore\_sync\connection_poo
                             l.py", line 216, in handle_request
                                 raise exc from None
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\httpcore\_sync\connection_poo
                             l.py", line 196, in handle_request
                                 response = connection.handle_request(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\httpcore\_sync\connection.py"
                             , line 99, in handle_request
                                 raise exc
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\httpcore\_sync\connection.py"
                             , line 76, in handle_request
                                 stream = self._connect(request)
                                          ^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\httpcore\_sync\connection.py"
                             , line 122, in _connect
                                 stream = self._network_backend.connect_tcp(**kwargs)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\httpcore\_backends\sync.py",
                             line 205, in connect_tcp
                                 with map_exceptions(exc_map):
                               File "contextlib.py", line 158, in __exit__
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\httpcore\_exceptions.py",
                             line 14, in map_exceptions
                                 raise to_exc(exc) from exc
                             httpcore.ConnectError: [WinError 10061] Aucune connexion n’a pu être établie car
                             l’ordinateur cible l’a expressément refusée

                             The above exception was the direct cause of the following exception:

                             Traceback (most recent call last):
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\openai\_base_client.py", line
                             973, in _request
                                 response = self._client.send(
                                            ^^^^^^^^^^^^^^^^^^
                               File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\httpx\_client.py",
                             line 926, in send
                                 response = self._send_handling_auth(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
                               File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\httpx\_client.py",
                             line 954, in _send_handling_auth
                                 response = self._send_handling_redirects(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\httpx\_client.py",
                             line 991, in _send_handling_redirects
                                 response = self._send_single_request(request)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\httpx\_client.py",
                             line 1027, in _send_single_request
                                 response = transport.handle_request(request)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\httpx\_transports\default.py"
                             , line 235, in handle_request
                                 with map_httpcore_exceptions():
                               File "contextlib.py", line 158, in __exit__
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\httpx\_transports\default.py"
                             , line 89, in map_httpcore_exceptions
                                 raise mapped_exc(message) from exc
                             httpx.ConnectError: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur
                             cible l’a expressément refusée

                             The above exception was the direct cause of the following exception:

                             Traceback (most recent call last):
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\griptape\tasks\base_task.py",
                             line 168, in execute
                                 self.output = self.run()
                                               ^^^^^^^^^^
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\griptape\tasks\prompt_task.py
                             ", line 81, in run
                                 message = self.prompt_driver.run(self.prompt_stack)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\griptape\common\observable.py
                             ", line 61, in __call__
                                 return Observability.observe(
                                        ^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\griptape\observability\observ
                             ability.py", line 36, in observe
                                 return driver.observe(call)
                                        ^^^^^^^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\griptape\drivers\observabilit
                             y\no_op_observability_driver.py", line 16, in observe
                                 return call()
                                        ^^^^^^
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\griptape\common\observable.py
                             ", line 29, in __call__
                                 return self.func(*args, **self.kwargs)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\griptape\drivers\prompt\base_
                             prompt_driver.py", line 66, in run
                                 for attempt in self.retrying():
                               File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\tenacity\__init__.py",
                             line 443, in __iter__
                                 do = self.iter(retry_state=retry_state)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\tenacity\__init__.py",
                             line 376, in iter
                                 result = action(retry_state)
                                          ^^^^^^^^^^^^^^^^^^^
                               File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\tenacity\__init__.py",
                             line 418, in exc_check
                                 raise retry_exc.reraise()
                                       ^^^^^^^^^^^^^^^^^^^
                               File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\tenacity\__init__.py",
                             line 185, in reraise
                                 raise self.last_attempt.result()
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File "concurrent\futures\_base.py", line 449, in result
                               File "concurrent\futures\_base.py", line 401, in __get_result
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\griptape\drivers\prompt\base_
                             prompt_driver.py", line 70, in run
                                 result = self.__process_stream(prompt_stack) if self.stream else
                             self.__process_run(prompt_stack)
                                                                                                  ^^^^^^^^^^^^^^^^^^^^^^
                             ^^^^^^^^^^
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\griptape\drivers\prompt\base_
                             prompt_driver.py", line 111, in __process_run
                                 return self.try_run(prompt_stack)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\griptape\common\observable.py
                             ", line 61, in __call__
                                 return Observability.observe(
                                        ^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\griptape\observability\observ
                             ability.py", line 36, in observe
                                 return driver.observe(call)
                                        ^^^^^^^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\griptape\drivers\observabilit
                             y\no_op_observability_driver.py", line 16, in observe
                                 return call()
                                        ^^^^^^
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\griptape\common\observable.py
                             ", line 29, in __call__
                                 return self.func(*args, **self.kwargs)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\griptape\drivers\prompt\opena
                             i_chat_prompt_driver.py", line 94, in try_run
                                 result = self.client.chat.completions.create(**self._base_params(prompt_stack))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\openai\_utils\_utils.py",
                             line 274, in wrapper
                                 return func(*args, **kwargs)
                                        ^^^^^^^^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\openai\resources\chat\complet
                             ions.py", line 704, in create
                                 return self._post(
                                        ^^^^^^^^^^^
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\openai\_base_client.py", line
                             1260, in post
                                 return cast(ResponseT, self.request(cast_to, opts, stream=stream,
                             stream_cls=stream_cls))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ^
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\openai\_base_client.py", line
                             937, in request
                                 return self._request(
                                        ^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\openai\_base_client.py", line
                             997, in _request
                                 return self._retry_request(
                                        ^^^^^^^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\openai\_base_client.py", line
                             1075, in _retry_request
                                 return self._request(
                                        ^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\openai\_base_client.py", line
                             997, in _request
                                 return self._retry_request(
                                        ^^^^^^^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\openai\_base_client.py", line
                             1075, in _retry_request
                                 return self._request(
                                        ^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\openai\_base_client.py", line
                             1007, in _request
                                 raise APIConnectionError(request=request) from err
                             openai.APIConnectionError: Connection error.
Prompt executed in 9.74 seconds
```

**Comment by shhlife** [comment]
This is very helpful showing the graph, will see if I can reproduce it now. thank you! :)

**Comment by shhlife** [comment]
Okay, I've been able to reproduce the bug - will work on it today!

**Comment by shhlife** [comment]
I found a workaround for now while I fix the config issue.

If you use individual drivers and the custom structure, it works as expected:

![image](https://github.com/user-attachments/assets/ea50484d-91da-4eee-b9e0-0ce3eb5f240f)

So hopefully this can allow you to move forward while I continue working on the actual solution.

**Comment by shhlife** [comment]
I've just pushed a new release which should fix this issue. Please give it a try and let me know how it goes! :)

**Comment by Hullabalo** [comment]
Wow, you're super fast. Both solutions (both workaround and release) work like a charm. Thanks!
By any chance, without any hurry, do you plan to extend the API call capabilities of LM Studio and Ollama drivers to specifically use min_p and top_k (I think I can live without the rest :))?

I'm also looking for a solution for logit_bias with LM Studio (I haven't really taken the time yet to see if and how this can be addressed with Ollama). I have some code here to extract logits inside comfy and pass them to LM Studio which works well, but I'm having issues with llama-cpp-python + cuBLAS, which doesn't work with some recent LLMs (without CUDA, I've had success, but it's a bit limiting). I think I'm asking for the moon here :)

Once again [RESOLVED], thanks a lot !

**Comment by shhlife** [comment]
Glad the solutions worked! :)

I've added `min_p` and `top_k` for a few other models, I'll add a task to add them for LM Studio and Ollama, thanks for that! :)

I haven't dug into anything with logits.. keep me up to date as you explore it!

thanks again! :)
