### ISSUE TITLE
Griptape not loading on fresh comfyui install

### ISSUE THREAD

**Issue by drelabre** [griptape-ai/ComfyUI-Griptape#151]
![image](https://github.com/user-attachments/assets/ac69046f-9260-4778-a1bf-1785f474a7ab)

I recently reinstalled comfy and griptape nodes, but griptape fails to load. Restarted, reinstalled nodes, to no avail.

**Comment by shhlife** [comment]
Thanks for the report! Can you see if you can send me the errors for when it's trying to install griptape? 

Cheers!

**Comment by shhlife** [comment]
Hi @drelabre - I have just pushed a new release that should resolve this issue. It had to do with not having an OPENAI_API_KEY in your environment. 

Please test out the latest and re-open this if it's still not working. :)

cheers!

**Comment by drelabre** [comment]
Just getting back to this now. Installed latest version, but still getting an error.

```
Cannot import G:\ComfyUI_windows_portable_OCT2024\ComfyUI\custom_nodes\ComfyUI-Griptape module for custom nodes: No module named 'griptape'
Traceback (most recent call last):
  File "G:\ComfyUI_windows_portable_OCT2024\ComfyUI\nodes.py", line 2018, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "G:\ComfyUI_windows_portable_OCT2024\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\__init__.py", line 9, in <module>
    from .IFChatPromptNode import IFChatPrompt
  File "G:\ComfyUI_windows_portable_OCT2024\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 14, in <module>
    from .send_request import send_request
  File "G:\ComfyUI_windows_portable_OCT2024\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\send_request.py", line 5, in <module>
    from .groq_api import send_groq_request
  File "G:\ComfyUI_windows_portable_OCT2024\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\groq_api.py", line 1, in <module>
    from groq import Groq
ModuleNotFoundError: No module named 'groq'
```

**Comment by drelabre** [comment]
![image](https://github.com/user-attachments/assets/26235d3a-2bf7-404e-95fe-7c58069cdbfd)

Griptape and another node don't load. Not sure if there's a shared dependency or discreet issues.

**Comment by drelabre** [comment]
@shhlife Not sure if you get these if it's marked closed. So just paging you to this thread.

**Comment by drelabre** [comment]
Solved.

User error on my part. I performed a fresh `pip install griptape` and i'm back in action.

**Comment by shhlife** [comment]
Thanks @drelabre !
