### ISSUE TITLE
Adding an extra embeddings?  /v1/embeddings/embeddings

### ISSUE THREAD

**Issue by mattjohnpowell** [griptape-ai/ComfyUI-Griptape#155]
I'm using the default LM Studio settings (In Griptape/ComfyUI and on LM Studio) BUt I'm getting the below error
And the text output from Griptape: Tool Task is: 'NoneType' object is not iterable

2024-11-04 14:02:44  [INFO]
[LM STUDIO SERVER] [ministral-8b-instruct-2410-hf-test] Generated prediction: {
  "id": "chatcmpl-lqt0tsei12h4xx6d2dz0d",
  "object": "chat.completion",
  "created": 1730728963,
  "model": "ministral-8b-instruct-2410-hf-test",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "{\"name\":\"WebScraperTool\",\"path\":\"get_content\",\"input\":{\"values\":{\"url\":\"https://bc.org/\"}}}"
      },
      "logprobs": null,
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 233,
    "completion_tokens": 29,
    "total_tokens": 262
  },
  "system_fingerprint": "ministral-8b-instruct-2410-hf-test"
}
2024-11-04 14:02:44  [INFO] [LM STUDIO SERVER] Client disconnected. Stopping generation..
2024-11-04 14:02:44 [ERROR] Unexpected endpoint or method. (POST /v1/embeddings/embeddings). Returning 200 anyway

**Comment by mattjohnpowell** [comment]
After running a second time, ComfyUI just crashed and now the nodes are not loaded (I'm guessing this is a separate issue (let me know if you want me to raise a second one)

   0.3 seconds (IMPORT FAILED): A:\diff\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape
   
   ...
   [Crystools INFO] 0) NVIDIA GeForce RTX 3060
[Crystools INFO] NVIDIA Driver: 566.03
[ComfyUI-Easy-Use] server: v1.2.4 Loaded
[ComfyUI-Easy-Use] web root: A:\diff\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 Loaded
Traceback (most recent call last):
  File "A:\diff\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "A:\diff\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape\__init__.py", line 13, in <module>
    from .nodes.agent.CreateAgent import CreateAgent
  File "A:\diff\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape\nodes\agent\CreateAgent.py", line 1, in <module>
    from .BaseAgent import BaseAgent
  File "A:\diff\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape\nodes\agent\BaseAgent.py", line 4, in <module>
    from griptape.drivers import DummyVectorStoreDriver
  File "A:\diff\ComfyUI_windows_portable\python_embeded\Lib\site-packages\griptape\drivers\__init__.py", line 2, in <module>
    from .prompt.openai_chat_prompt_driver import OpenAiChatPromptDriver
  File "A:\diff\ComfyUI_windows_portable\python_embeded\Lib\site-packages\griptape\drivers\prompt\openai_chat_prompt_driver.py", line 7, in <module>
    import openai
  File "A:\diff\ComfyUI_windows_portable\python_embeded\Lib\site-packages\openai\__init__.py", line 8, in <module>
    from . import types
  File "A:\diff\ComfyUI_windows_portable\python_embeded\Lib\site-packages\openai\types\__init__.py", line 5, in <module>
    from .batch import Batch as Batch
  File "A:\diff\ComfyUI_windows_portable\python_embeded\Lib\site-packages\openai\types\batch.py", line 7, in <module>
    from .._models import BaseModel
  File "A:\diff\ComfyUI_windows_portable\python_embeded\Lib\site-packages\openai\_models.py", line 36, in <module>
    from ._utils import (
  File "A:\diff\ComfyUI_windows_portable\python_embeded\Lib\site-packages\openai\_utils\__init__.py", line 1, in <module>
    from ._sync import asyncify as asyncify
  File "A:\diff\ComfyUI_windows_portable\python_embeded\Lib\site-packages\openai\_utils\_sync.py", line 7, in <module>
    import anyio
ModuleNotFoundError: No module named 'anyio'

Cannot import A:\diff\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape module for custom nodes: No module named 'anyio'
[Moondream] trying to update model versions...ok
[Moondream] found model versions: 2024-03-04, 2024-03-06, 2024-03-13, 2024-04-02, 2024-05-08, 2024-05-20, 2024-07-23, 2024-08-26
....

**Comment by shhlife** [comment]
I'll take a look and see what's going on - thank you for the report.

**Comment by mattjohnpowell** [comment]
I cut down the url just for the privacy of the website that I'm scraping. even example.com would be fine for testing.

The model I used was Ministral, which is said to be good at function calling (I'm assuming that's how tools are accessed but I may be wrong)
I will try Llama 3.2 3B but can't get 11B yet

**Comment by shhlife** [comment]
Cool - I've found that some websites have trouble with scraping, and with lmstudio I'm unable to get function calling to work. llama3.2 does seem to work with Ollama for most sites, but while testing this I discovered a bug that for some reason the websites aren't coming through correctly when adding the http: in front of the website.

For example, saying "describe the contents of griptape.ai" worked but "http://griptape.ai" did not.

I'll be working on that now.

**Comment by shhlife** [comment]
Okay, I'm about to push a fix for the input bug, but in the meantime tested Ollama with mistral and it seemed to work - although I had to try a few different prompts to get it to work as expected. These smaller models aren't as good at figuring out intent as the larger ones.

![image](https://github.com/user-attachments/assets/c746b25b-7481-44e6-85a5-d9e5741e67ca)

**Comment by mattjohnpowell** [comment]
Just to let you know, LM Studio will soon release (are currently running beta tests) on tool use.  Thanks for the answers.

**Comment by shhlife** [comment]
Awesome! as soon as it's released we can give it a go again - definitely re-open this when it's ready (if I don't remember to do it first :) )
