### ISSUE TITLE
using merge text with reroutes and undo is corrupting workflows.

### ISSUE THREAD

**Issue by spiraloid** [griptape-ai/ComfyUI-Griptape#161]
create some Griptape Generate text nodes and connect them to a Griptape Merge Text node.  connect the output to a reroute.  try to connect to a Griptape Display text node.  You will get an error.  all your groups will be removed and the workflow will be corrupt. 

![image](https://github.com/user-attachments/assets/7e497d25-5dd3-4131-b1bc-08e01fb631f5)

TypeError: Cannot read properties of undefined (reading 'constructor')
    at RerouteNode.onConnectionsChange (http://127.0.0.1:8188/assets/index-BReiUkk9.js:3859:36)
    at RerouteNode.configure (http://127.0.0.1:8188/assets/index-BHayQCxv.js:59903:35)
    at LGraph.configure (http://127.0.0.1:8188/assets/index-BHayQCxv.js:69309:17)
    at LGraph.configure (http://127.0.0.1:8188/assets/index-BHayQCxv.js:78040:26)
    at LGraph.configure (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/reroutePrimitive.js:14:29)
    at ComfyApp.loadGraphData (http://127.0.0.1:8188/assets/index-BHayQCxv.js:78562:18)
    at async app2.loadGraphData (http://127.0.0.1:8188/assets/index-BHayQCxv.js:73427:18)
    at async app.loadGraphData (http://127.0.0.1:8188/extensions/ComfyUI-Manager/components-manager.js:773:9)
    at async Proxy.load (http://127.0.0.1:8188/assets/index-BHayQCxv.js:73835:7)

**Comment by shhlife** [comment]
Yikes! I’ll take a look first thing in the morning - thank you!Sent from my iPhoneOn 8 Nov 2024, at 10:44 AM, Spiraloid ***@***.***> wrote:﻿
create some Griptape Generate text nodes and connect them to a Griptape Merge Text node.  connect the output to a reroute.  try to connect to a Griptape Display text node.  You will get an error.  all your groups will be removed and the workflow will be corrupt.
image.png (view on web)
TypeError: Cannot read properties of undefined (reading 'constructor')
at RerouteNode.onConnectionsChange (http://127.0.0.1:8188/assets/index-BReiUkk9.js:3859:36)
at RerouteNode.configure (http://127.0.0.1:8188/assets/index-BHayQCxv.js:59903:35)
at LGraph.configure (http://127.0.0.1:8188/assets/index-BHayQCxv.js:69309:17)
at LGraph.configure (http://127.0.0.1:8188/assets/index-BHayQCxv.js:78040:26)
at LGraph.configure (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/reroutePrimitive.js:14:29)
at ComfyApp.loadGraphData (http://127.0.0.1:8188/assets/index-BHayQCxv.js:78562:18)
at async app2.loadGraphData (http://127.0.0.1:8188/assets/index-BHayQCxv.js:73427:18)
at async app.loadGraphData (http://127.0.0.1:8188/extensions/ComfyUI-Manager/components-manager.js:773:9)
at async Proxy.load (http://127.0.0.1:8188/assets/index-BHayQCxv.js:73835:7)

**Comment by shhlife** [comment]
okay, was able to reproduce the bug.. will dig in

**Comment by shhlife** [comment]
I think I've fixed the issue with the output of the merge text nodes breaking, but haven't been able to reproduce the group node issue you were seeing.

Can you send me a screenshot of the how it was breaking group nodes?

one thing I also noticed, is because of the way ComfyUI handles group nodes, and the way I'm dynamically creating the inputs on the merge node, adding merge nodes to group nodes doesn't work well. In fact the new input nodes don't seem to work. 

I might need to think about handling the combine nodes differently where instead of *creating* and *deleting* the input nodes dynamically, we just *hide* and *show* them.

Unfortunately this means i need to make *n* number of inputs..

what's the most number of inputs you currently have on your merge nodes?

**Comment by shhlife** [comment]
btw - I just pushed a release that hopefully fixes the bug - please try it out

**Comment by shhlife** [comment]
@spiraloid can you give this a shot and see if it solved the bug?

**Comment by shhlife** [comment]
sweet!
