### ISSUE TITLE
On trying the create image from text I get an error

### ISSUE THREAD

**Issue by serget2** [griptape-ai/ComfyUI-Griptape#164]
# ComfyUI Error Report
## Error Details
- **Node Type:** Griptape Create: Image from Text
- **Exception Type:** FileNotFoundError
- **Exception Message:** [Errno 2] No such file or directory: 'D:\\Automatic1.1.1.1\\ComfyUI_windows_portable\\ComfyUI\\temp\\5e55242278eb4332a922ab0db7815ab5'
## Stack Trace
```
  File "D:\Automatic1.1.1.1\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\Automatic1.1.1.1\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\Automatic1.1.1.1\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\Automatic1.1.1.1\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\Automatic1.1.1.1\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape\nodes\tasks\gtUIPromptImageGenerationTask.py", line 101, in run
    output_image, output_mask = image_path_to_output(image_path)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\Automatic1.1.1.1\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape\nodes\utilities.py", line 71, in image_path_to_output
    img = Image.open(image_path)
          ^^^^^^^^^^^^^^^^^^^^^^

  File "D:\Automatic1.1.1.1\ComfyUI_windows_portable\python_embeded\Lib\site-packages\PIL\Image.py", line 3431, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.7-22-g122c9ca
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.5.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12884377600
  - **VRAM Free:** 11709448180
  - **Torch VRAM Total:** 100663296
  - **Torch VRAM Free:** 67108852

## Logs
```
2024-11-17T18:46:35.702133 - )2024-11-17T18:46:35.702133 -                                                         2024-11-17T18:46:35.702133 - 
2024-11-17T18:46:35.703133 -                       2024-11-17T18:46:35.703133 -          2024-11-17T18:46:35.703133 -              ^^^^^^^^^^^^^^^^^^^                                                        2024-11-17T18:46:35.703133 - 
2024-11-17T18:46:35.704132 -                       2024-11-17T18:46:35.704132 -          2024-11-17T18:46:35.704132 -   File                                                                                  2024-11-17T18:46:35.704132 - 
2024-11-17T18:46:35.705133 -                       2024-11-17T18:46:35.705133 -          2024-11-17T18:46:35.705133 - "D:\Automatic1.1.1.1\ComfyUI_windows_portable\python_embeded\Lib\site-packages\tenacity\2024-11-17T18:46:35.705133 - 
2024-11-17T18:46:35.706133 -                       2024-11-17T18:46:35.706133 -          2024-11-17T18:46:35.706133 - __init__.py"2024-11-17T18:46:35.706133 - , line 2024-11-17T18:46:35.706133 - 4182024-11-17T18:46:35.706133 - , in exc_check                                                    2024-11-17T18:46:35.707133 - 
2024-11-17T18:46:35.707133 -                       2024-11-17T18:46:35.707133 -          2024-11-17T18:46:35.707133 -     raise 2024-11-17T18:46:35.707133 - retry_exc.reraise2024-11-17T18:46:35.708132 - (2024-11-17T18:46:35.708132 - )2024-11-17T18:46:35.708132 -                                                            2024-11-17T18:46:35.708132 - 
2024-11-17T18:46:35.708132 -                       2024-11-17T18:46:35.708132 -          2024-11-17T18:46:35.709132 -           ^^^^^^^^^^^^^^^^^^^                                                           2024-11-17T18:46:35.709132 - 
2024-11-17T18:46:35.709132 -                       2024-11-17T18:46:35.709132 -          2024-11-17T18:46:35.709132 -   File                                                                                  2024-11-17T18:46:35.709132 - 
2024-11-17T18:46:35.710133 -                       2024-11-17T18:46:35.710133 -          2024-11-17T18:46:35.710133 - "D:\Automatic1.1.1.1\ComfyUI_windows_portable\python_embeded\Lib\site-packages\tenacity\2024-11-17T18:46:35.710133 - 
2024-11-17T18:46:35.711133 -                       2024-11-17T18:46:35.711133 -          2024-11-17T18:46:35.711133 - __init__.py"2024-11-17T18:46:35.711133 - , line 2024-11-17T18:46:35.711133 - 1852024-11-17T18:46:35.711133 - , in reraise                                                      2024-11-17T18:46:35.712133 - 
2024-11-17T18:46:35.712133 -                       2024-11-17T18:46:35.712133 -          2024-11-17T18:46:35.712133 -     raise 2024-11-17T18:46:35.712133 - self.last_attempt.result2024-11-17T18:46:35.715132 - (2024-11-17T18:46:35.715132 - )2024-11-17T18:46:35.715132 -                                                     2024-11-17T18:46:35.715132 - 
2024-11-17T18:46:35.716132 -                       2024-11-17T18:46:35.716132 -          2024-11-17T18:46:35.716132 -           ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                    2024-11-17T18:46:35.716132 - 
2024-11-17T18:46:35.716132 -                       2024-11-17T18:46:35.717132 -          2024-11-17T18:46:35.717132 -   File 2024-11-17T18:46:35.717132 - "concurrent\futures\_base.py"2024-11-17T18:46:35.717132 - , line 2024-11-17T18:46:35.717132 - 4492024-11-17T18:46:35.717132 - , in result                               2024-11-17T18:46:35.717132 - 
2024-11-17T18:46:35.718132 -                       2024-11-17T18:46:35.718132 -          2024-11-17T18:46:35.718132 -   File 2024-11-17T18:46:35.718132 - "concurrent\futures\_base.py"2024-11-17T18:46:35.718132 - , line 2024-11-17T18:46:35.718132 - 4012024-11-17T18:46:35.718132 - , in __get_result                         2024-11-17T18:46:35.719132 - 
2024-11-17T18:46:35.719132 -                       2024-11-17T18:46:35.719132 -          2024-11-17T18:46:35.719132 -   File                                                                                  2024-11-17T18:46:35.719132 - 
2024-11-17T18:46:35.720133 -                       2024-11-17T18:46:35.720133 -          2024-11-17T18:46:35.720133 - "D:\Automatic1.1.1.1\ComfyUI_windows_portable\python_embeded\Lib\site-packages\griptape\2024-11-17T18:46:35.720133 - 
2024-11-17T18:46:35.721132 -                       2024-11-17T18:46:35.721132 -          2024-11-17T18:46:35.721132 - drivers\image_generation\base_image_generation_driver.py"2024-11-17T18:46:35.721132 - , line 2024-11-17T18:46:35.721132 - 302024-11-17T18:46:35.721132 - , in run_text_to_image2024-11-17T18:46:35.721132 - 
2024-11-17T18:46:35.722133 -                       2024-11-17T18:46:35.722133 -          2024-11-17T18:46:35.722133 -     result = 2024-11-17T18:46:35.722133 - self.try_text_to_image2024-11-17T18:46:35.722133 - (2024-11-17T18:46:35.723132 - prompts, negative_prompts2024-11-17T18:46:35.723132 - )2024-11-17T18:46:35.723132 -                           2024-11-17T18:46:35.723132 - 
2024-11-17T18:46:35.723132 -                       2024-11-17T18:46:35.724134 -          2024-11-17T18:46:35.724134 -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                          2024-11-17T18:46:35.724134 - 
2024-11-17T18:46:35.724134 -                       2024-11-17T18:46:35.724134 -          2024-11-17T18:46:35.724134 -   File                                                                                  2024-11-17T18:46:35.725133 - 
2024-11-17T18:46:35.725133 -                       2024-11-17T18:46:35.726132 -          2024-11-17T18:46:35.726132 - "D:\Automatic1.1.1.1\ComfyUI_windows_portable\python_embeded\Lib\site-packages\griptape\2024-11-17T18:46:35.726132 - 
2024-11-17T18:46:35.726132 -                       2024-11-17T18:46:35.726132 -          2024-11-17T18:46:35.726132 - drivers\image_generation\openai_image_generation_driver.py"2024-11-17T18:46:35.727132 - , line 2024-11-17T18:46:35.727132 - 732024-11-17T18:46:35.727132 - , in                2024-11-17T18:46:35.727132 - 
2024-11-17T18:46:35.727132 -                       2024-11-17T18:46:35.727132 -          2024-11-17T18:46:35.728133 - try_text_to_image                                                                       2024-11-17T18:46:35.728133 - 
2024-11-17T18:46:35.728133 -                       2024-11-17T18:46:35.728133 -          2024-11-17T18:46:35.728133 -     response = 2024-11-17T18:46:35.729134 - self.client.images.generate2024-11-17T18:46:35.731134 - (2024-11-17T18:46:35.731134 -                                              2024-11-17T18:46:35.731134 - 
2024-11-17T18:46:35.732133 -                       2024-11-17T18:46:35.732133 -          2024-11-17T18:46:35.732133 -                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                             2024-11-17T18:46:35.732133 - 
2024-11-17T18:46:35.732133 -                       2024-11-17T18:46:35.732133 -          2024-11-17T18:46:35.733131 -   File                                                                                  2024-11-17T18:46:35.733131 - 
2024-11-17T18:46:35.733131 -                       2024-11-17T18:46:35.733131 -          2024-11-17T18:46:35.733131 - "D:\Automatic1.1.1.1\ComfyUI_windows_portable\python_embeded\Lib\site-packages\openai\re2024-11-17T18:46:35.733131 - 
2024-11-17T18:46:35.734133 -                       2024-11-17T18:46:35.734133 -          2024-11-17T18:46:35.734133 - sources\images.py"2024-11-17T18:46:35.734133 - , line 2024-11-17T18:46:35.734133 - 2602024-11-17T18:46:35.734133 - , in generate                                               2024-11-17T18:46:35.734133 - 
2024-11-17T18:46:35.735132 -                       2024-11-17T18:46:35.735132 -          2024-11-17T18:46:35.735132 -     return 2024-11-17T18:46:35.735132 - self._post2024-11-17T18:46:35.735132 - (2024-11-17T18:46:35.736134 -                                                                   2024-11-17T18:46:35.736134 - 
2024-11-17T18:46:35.736134 -                       2024-11-17T18:46:35.736134 -          2024-11-17T18:46:35.736134 -            ^^^^^^^^^^^                                                                  2024-11-17T18:46:35.737132 - 
2024-11-17T18:46:35.738133 -                       2024-11-17T18:46:35.738133 -          2024-11-17T18:46:35.738133 -   File                                                                                  2024-11-17T18:46:35.738133 - 
2024-11-17T18:46:35.739133 -                       2024-11-17T18:46:35.739133 -          2024-11-17T18:46:35.739133 - "D:\Automatic1.1.1.1\ComfyUI_windows_portable\python_embeded\Lib\site-packages\openai\_b2024-11-17T18:46:35.739133 - 
2024-11-17T18:46:35.740133 -                       2024-11-17T18:46:35.740133 -          2024-11-17T18:46:35.740133 - ase_client.py"2024-11-17T18:46:35.741133 - , line 2024-11-17T18:46:35.741133 - 12332024-11-17T18:46:35.741133 - , in post                                                      2024-11-17T18:46:35.741133 - 
2024-11-17T18:46:35.741133 -                       2024-11-17T18:46:35.741133 -          2024-11-17T18:46:35.741133 -     return 2024-11-17T18:46:35.742132 - cast2024-11-17T18:46:35.742132 - (2024-11-17T18:46:35.742132 - ResponseT, 2024-11-17T18:46:35.742132 - self.request2024-11-17T18:46:35.742132 - (2024-11-17T18:46:35.742132 - cast_to, opts, 2024-11-17T18:46:35.742132 - stream2024-11-17T18:46:35.742132 - =2024-11-17T18:46:35.742132 - stream2024-11-17T18:46:35.742132 - ,                   2024-11-17T18:46:35.743132 - 
2024-11-17T18:46:35.743132 -                       2024-11-17T18:46:35.743132 -          2024-11-17T18:46:35.743132 - stream_cls2024-11-17T18:46:35.743132 - =2024-11-17T18:46:35.744133 - stream_cls2024-11-17T18:46:35.744133 - )2024-11-17T18:46:35.744133 - )2024-11-17T18:46:35.744133 -                                                                  2024-11-17T18:46:35.744133 - 
2024-11-17T18:46:35.744133 -                       2024-11-17T18:46:35.745132 -          2024-11-17T18:46:35.747134 -                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^2024-11-17T18:46:35.747134 - 
2024-11-17T18:46:35.748134 -                       2024-11-17T18:46:35.748134 -          2024-11-17T18:46:35.748134 - ^^^^                                                                                    2024-11-17T18:46:35.748134 - 
2024-11-17T18:46:35.749141 -                       2024-11-17T18:46:35.749141 -          2024-11-17T18:46:35.749141 -   File                                                                                  2024-11-17T18:46:35.749141 - 
2024-11-17T18:46:35.749141 -                       2024-11-17T18:46:35.750132 -          2024-11-17T18:46:35.750132 - "D:\Automatic1.1.1.1\ComfyUI_windows_portable\python_embeded\Lib\site-packages\openai\_b2024-11-17T18:46:35.750132 - 
2024-11-17T18:46:35.750132 -                       2024-11-17T18:46:35.750132 -          2024-11-17T18:46:35.751132 - ase_client.py"2024-11-17T18:46:35.751132 - , line 2024-11-17T18:46:35.751132 - 9222024-11-17T18:46:35.751132 - , in request                                                    2024-11-17T18:46:35.751132 - 
2024-11-17T18:46:35.751132 -                       2024-11-17T18:46:35.752132 -          2024-11-17T18:46:35.752132 -     return 2024-11-17T18:46:35.752132 - self._request2024-11-17T18:46:35.752132 - (2024-11-17T18:46:35.752132 -                                                                2024-11-17T18:46:35.752132 - 
2024-11-17T18:46:35.753134 -                       2024-11-17T18:46:35.753134 -          2024-11-17T18:46:35.753134 -            ^^^^^^^^^^^^^^                                                               2024-11-17T18:46:35.753134 - 
2024-11-17T18:46:35.754133 -                       2024-11-17T18:46:35.754133 -          2024-11-17T18:46:35.754133 -   File                                                                                  2024-11-17T18:46:35.754133 - 
2024-11-17T18:46:35.754133 -                       2024-11-17T18:46:35.754133 -          2024-11-17T18:46:35.755133 - "D:\Automatic1.1.1.1\ComfyUI_windows_portable\python_embeded\Lib\site-packages\openai\_b2024-11-17T18:46:35.755133 - 
2024-11-17T18:46:35.755133 -                       2024-11-17T18:46:35.756133 -          2024-11-17T18:46:35.756133 - ase_client.py"2024-11-17T18:46:35.756133 - , line 2024-11-17T18:46:35.756133 - 10132024-11-17T18:46:35.756133 - , in _request                                                  2024-11-17T18:46:35.756133 - 
2024-11-17T18:46:35.757132 -                       2024-11-17T18:46:35.757132 -          2024-11-17T18:46:35.757132 -     raise 2024-11-17T18:46:35.757132 - self._make_status_error_from_response2024-11-17T18:46:35.757132 - (2024-11-17T18:46:35.757132 - err.response2024-11-17T18:46:35.757132 - )2024-11-17T18:46:35.757132 -  from 2024-11-17T18:46:35.757132 - None2024-11-17T18:46:35.758132 -                  2024-11-17T18:46:35.758132 - 
2024-11-17T18:46:35.758132 -                       2024-11-17T18:46:35.758132 -          2024-11-17T18:46:35.758132 - openai.BadRequestError: Error code: 2024-11-17T18:46:35.758132 - 4002024-11-17T18:46:35.759134 -  - 2024-11-17T18:46:35.759134 - {2024-11-17T18:46:35.759134 - 'error'2024-11-17T18:46:35.759134 - : 2024-11-17T18:46:35.759134 - {2024-11-17T18:46:35.759134 - 'code'2024-11-17T18:46:35.759134 - : 2024-11-17T18:46:35.759134 - None2024-11-17T18:46:35.760133 - , 2024-11-17T18:46:35.762132 - 'message'2024-11-17T18:46:35.762132 - : 2024-11-17T18:46:35.762132 - 'Prompt 2024-11-17T18:46:35.762132 -   2024-11-17T18:46:35.762132 - 
2024-11-17T18:46:35.762132 -                       2024-11-17T18:46:35.762132 -          2024-11-17T18:46:35.763131 - must be length 1000 or less. Your prompt length is 1192. Please reduce your prompt 2024-11-17T18:46:35.763131 -      2024-11-17T18:46:35.763131 - 
2024-11-17T18:46:35.764131 -                       2024-11-17T18:46:35.764131 -          2024-11-17T18:46:35.764131 - length.'2024-11-17T18:46:35.764131 - , 2024-11-17T18:46:35.764131 - 'param'2024-11-17T18:46:35.764131 - : 2024-11-17T18:46:35.765134 - None2024-11-17T18:46:35.765134 - , 2024-11-17T18:46:35.765134 - 'type'2024-11-17T18:46:35.765134 - : 2024-11-17T18:46:35.765134 - 'invalid_request_error'2024-11-17T18:46:35.765134 - }2024-11-17T18:46:35.765134 - }2024-11-17T18:46:35.765134 -                               2024-11-17T18:46:35.765134 - 
2024-11-17T18:46:35.769131 - !!! Exception during processing !!! [Errno 2] No such file or directory: 'D:\\Automatic1.1.1.1\\ComfyUI_windows_portable\\ComfyUI\\temp\\5e55242278eb4332a922ab0db7815ab5'
2024-11-17T18:46:35.770132 - Traceback (most recent call last):
  File "D:\Automatic1.1.1.1\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Automatic1.1.1.1\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Automatic1.1.1.1\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\Automatic1.1.1.1\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Automatic1.1.1.1\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape\nodes\tasks\gtUIPromptImageGenerationTask.py", line 101, in run
    output_image, output_mask = image_path_to_output(image_path)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Automatic1.1.1.1\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Griptape\nodes\utilities.py", line 71, in image_path_to_output
    img = Image.open(image_path)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Automatic1.1.1.1\ComfyUI_windows_portable\python_embeded\Lib\site-packages\PIL\Image.py", line 3431, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Automatic1.1.1.1\\ComfyUI_windows_portable\\ComfyUI\\temp\\5e55242278eb4332a922ab0db7815ab5'

2024-11-17T18:46:35.772132 - Prompt executed in 69.04 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":7,"last_link_id":5,"nodes":[{"id":2,"type":"Griptape Agent Config: Ollama Drivers","pos":{"0":72,"1":88},"size":{"0":466.1999816894531,"1":322},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"CONFIG","type":"CONFIG","links":[],"slot_index":0}],"properties":{"Node name for S&R":"Griptape Agent Config: Ollama Drivers"},"widgets_values":["http://127.0.0.1","11434","Prompt Driver","llama3.2:latest",10,0.1,2048,"fixed",true,-1,"Embedding Driver",""]},{"id":4,"type":"Griptape Agent Config: Google Drivers","pos":{"0":38,"1":458},"size":{"0":466.1999816894531,"1":370},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"CONFIG","type":"CONFIG","links":[3],"slot_index":0}],"properties":{"Node name for S&R":"Griptape Agent Config: Google Drivers"},"widgets_values":["Prompt Driver","gemini-1.5-pro",10,0.1,2048,"fixed",true,-1,"GOOGLE_API_KEY",0.999,250,"Embedding Driver","models/embedding-001","RETRIEVAL_QUERY"]},{"id":5,"type":"Griptape Display: Image","pos":{"0":1568,"1":366},"size":{"0":289.79998779296875,"1":26},"flags":{},"order":4,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":4,"shape":7}],"outputs":[{"name":"OUTPUT","type":"IMAGE","links":null}],"properties":{"Node name for S&R":"Griptape Display: Image"}},{"id":1,"type":"Griptape Create: Image from Text","pos":{"0":1122,"1":363},"size":[403.1999816894531,200],"flags":{},"order":3,"mode":0,"inputs":[{"name":"agent","type":"AGENT","link":null,"shape":7},{"name":"driver","type":"DRIVER","link":null,"shape":7},{"name":"input_string","type":"STRING","link":2,"widget":{"name":"input_string"},"shape":7}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[4],"slot_index":0},{"name":"AGENT","type":"AGENT","links":null},{"name":"file_path","type":"STRING","links":[],"slot_index":2}],"properties":{"Node name for S&R":"Griptape Create: Image from Text"},"widgets_values":["Side view portrait of an ancient Grim Reaper-like figure looking away from viewer standing in a desolate wasteland, wearing a dark, decaying cloak, holding a large scythe resting on his shoulder. The blade of the scythe has a faint glowing green energy, tendrils of light swirling from the blade, cracked earth and faint black mist beneath, skeletal face shrouded in shadow, mystical and grim, epic dark fantasy art style. His cloak swirls in the wind.",""]},{"id":3,"type":"Griptape Create: Agent","pos":{"0":630,"1":366},"size":[400,200],"flags":{},"order":2,"mode":0,"inputs":[{"name":"agent","type":"AGENT","link":null,"shape":7},{"name":"config","type":"CONFIG","link":3,"shape":7},{"name":"tools","type":"TOOL_LIST","link":null,"shape":7},{"name":"rulesets","type":"RULESET","link":null,"shape":7},{"name":"input_string","type":"STRING","link":null,"widget":{"name":"input_string"},"shape":7}],"outputs":[{"name":"OUTPUT","type":"STRING","links":[2],"slot_index":0},{"name":"AGENT","type":"AGENT","links":[],"slot_index":1}],"properties":{"Node name for S&R":"Griptape Create: Agent"},"widgets_values":["","Save impages to this path:D:\\Automatic1.1.1.1\\ComfyUI_windows_portable\\ComfyUI\\output\\"]}],"links":[[2,3,0,1,2,"STRING"],[3,4,0,3,1,"CONFIG"],[4,1,0,5,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":2.1435888100000016,"offset":[-775.26751631998,-252.95443350443685]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by shhlife** [comment]
Looking at the logs I noticed this section:

```
2024-11-17T18:46:35.758132 -                       2024-11-17T18:46:35.758132 -          2024-11-17T18:46:35.758132 - openai.BadRequestError: Error code: 2024-11-17T18:46:35.758132 - 4002024-11-17T18:46:35.759134 -  - 2024-11-17T18:46:35.759134 - {2024-11-17T18:46:35.759134 - 'error'2024-11-17T18:46:35.759134 - : 2024-11-17T18:46:35.759134 - {2024-11-17T18:46:35.759134 - 'code'2024-11-17T18:46:35.759134 - : 2024-11-17T18:46:35.759134 - None2024-11-17T18:46:35.760133 - , 2024-11-17T18:46:35.762132 - 'message'2024-11-17T18:46:35.762132 - : 2024-11-17T18:46:35.762132 - 'Prompt 2024-11-17T18:46:35.762132 -   2024-11-17T18:46:35.762132 - 
2024-11-17T18:46:35.762132 -                       2024-11-17T18:46:35.762132 -          2024-11-17T18:46:35.763131 - must be length 1000 or less. Your prompt length is 1192. Please reduce your prompt 2024-11-17T18:46:35.763131 -      2024-11-17T18:46:35.763131 - 
2024-11-17T18:46:35.764131 -                       2024-11-17T18:46:35.764131 -          2024-11-17T18:46:35.764131 - length.'2024-11-17T18:46:35.764131 - , 2024-11-17T18:46:35.764131 - 'param'2024-11-17T18:46:35.764131 - : 2024-11-17T18:46:35.765134 - None2024-11-17T18:46:35.765134 - , 2024-11-17T18:46:35.765134 - 'type'2024-11-17T18:46:35.765134 - : 2024-11-17T18:46:35.765134 - 'invalid_request_error'2024-11-17T18:46:35.765134 - }2024-11-17T18:46:35.765134 - }2024-11-17T18:46:35.765134 -                               2024-11-17T18:46:35.765134 - 
2024-11-17T18:46:35.769131 - !!! Exception during processing !!! [Errno 2] No such file or directory: 'D:\\Automatic1.1.1.1\\ComfyUI_windows_portable\\ComfyUI\\temp\\5e55242278eb4332a922ab0db7815ab5'
```

Hidden in that verbose, hard to deduce error is a key bit of info.. `must be length 1000 or less. Your prompt length is 1192. Please reduce your prompt `

OpenAI requires prompts that are a bit shorter for image generation. It looks like yours is just a little too long.

Can you try shortening the prompt a little and let me know if that works?

**Comment by serget2** [comment]
Woaw I didn't know you would answer this quickly, So I started a long run of 100 prompts in FluxI will try it when those are done, thank you for replying so quickly, and next time enjoy your sunday bruh, no need to jump that quickly to help me I am patient, this is fun for me

**Comment by shhlife** [comment]
no worries, let me know when you have time :)

**Comment by serget2** [comment]
OK tried again sorry for the late response, I get billimg limit reached but it is my own Ollama 3.2 latest, so that can't be right, also couldn't make it shorter then "a pencil", but I limited the prompt to 300 words and it is still too big

![afbeelding](https://github.com/user-attachments/assets/e4def69f-3a2b-462a-956b-4d45f15f6069)

**Comment by serget2** [comment]
No biggy I used Griptape in conjunction with flux and I have gotten epic images the likes I never had before (https://civitai.com/user/serget2/images). So I'll just continue with the next griptape videos and keep this in mind

**Comment by shhlife** [comment]
very nice! :)

btw, in the next release there are nodes to use Flux API with Griptape if you want. :)
