### ISSUE TITLE
Hello! iam having issues with GripTape in Comfyui, created an API Key and added in the settings but i can't access gpt-4o

### ISSUE THREAD

**Issue by claudiojarrao** [griptape-ai/ComfyUI-Griptape#165]
got prompt
STRING: STRING='hello\n'
input_string: input_string=None
Agent Prompt Driver Name: agent_prompt_driver_name='OpenAiChatPromptDriver'
[11/20/24 17:52:29] INFO     PromptTask dc956ed6838b47d59935cd8114445b03
                             Input: hello
HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 404 Not Found"
[11/20/24 17:52:30] ERROR    PromptTask dc956ed6838b47d59935cd8114445b03
                             Error code: 404 - {'error': {'message': 'The model `gpt-4o` does not exist or you do not
                             have access to it.', 'type': 'invalid_request_error', 'param': None, 'code':
                             'model_not_found'}}
                             Traceback (most recent call last):
                               File
                             "D:\ComfyUI-Studio-v88\App\python_embeded\Lib\site-packages\griptape\tasks\base_task.py",
                             line 158, in run
                                 self.output = self.try_run()
                                               ^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI-Studio-v88\App\python_embeded\Lib\site-packages\griptape\tasks\prompt_task.py",
                             line 98, in try_run
                                 message = self.prompt_driver.run(self.prompt_stack)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI-Studio-v88\App\python_embeded\Lib\site-packages\griptape\common\decorators.py",
                             line 14, in decorator
                                 return Observability.observe(
                                        ^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI-Studio-v88\App\python_embeded\Lib\site-packages\griptape\observability\observab
                             ility.py", line 36, in observe
                                 return driver.observe(call)
                                        ^^^^^^^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI-Studio-v88\App\python_embeded\Lib\site-packages\griptape\drivers\observability\
                             no_op_observability_driver.py", line 16, in observe
                                 return call()
                                        ^^^^^^
                               File
                             "D:\ComfyUI-Studio-v88\App\python_embeded\Lib\site-packages\griptape\common\observable.py",
                             line 19, in __call__
                                 return self.func(*self.args, **self.kwargs)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI-Studio-v88\App\python_embeded\Lib\site-packages\griptape\drivers\prompt\base_pr
                             ompt_driver.py", line 75, in run
                                 for attempt in self.retrying():
                               File "D:\ComfyUI-Studio-v88\App\python_embeded\Lib\site-packages\tenacity\__init__.py",
                             line 443, in __iter__
                                 do = self.iter(retry_state=retry_state)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File "D:\ComfyUI-Studio-v88\App\python_embeded\Lib\site-packages\tenacity\__init__.py",
                             line 376, in iter
                                 result = action(retry_state)
                                          ^^^^^^^^^^^^^^^^^^^
                               File "D:\ComfyUI-Studio-v88\App\python_embeded\Lib\site-packages\tenacity\__init__.py",
                             line 398, in <lambda>
                                 self._add_action_func(lambda rs: rs.outcome.result())
                                                                  ^^^^^^^^^^^^^^^^^^^
                               File "concurrent\futures\_base.py", line 449, in result
                               File "concurrent\futures\_base.py", line 401, in __get_result
                               File
                             "D:\ComfyUI-Studio-v88\App\python_embeded\Lib\site-packages\griptape\drivers\prompt\base_pr
                             ompt_driver.py", line 79, in run
                                 result = self.__process_stream(prompt_stack) if self.stream else
                             self.__process_run(prompt_stack)
                                                                                                  ^^^^^^^^^^^^^^^^^^^^^^
                             ^^^^^^^^^^
                               File
                             "D:\ComfyUI-Studio-v88\App\python_embeded\Lib\site-packages\griptape\drivers\prompt\base_pr
                             ompt_driver.py", line 120, in __process_run
                                 return self.try_run(prompt_stack)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI-Studio-v88\App\python_embeded\Lib\site-packages\griptape\common\decorators.py",
                             line 14, in decorator
                                 return Observability.observe(
                                        ^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI-Studio-v88\App\python_embeded\Lib\site-packages\griptape\observability\observab
                             ility.py", line 36, in observe
                                 return driver.observe(call)
                                        ^^^^^^^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI-Studio-v88\App\python_embeded\Lib\site-packages\griptape\drivers\observability\
                             no_op_observability_driver.py", line 16, in observe
                                 return call()
                                        ^^^^^^
                               File
                             "D:\ComfyUI-Studio-v88\App\python_embeded\Lib\site-packages\griptape\common\observable.py",
                             line 19, in __call__
                                 return self.func(*self.args, **self.kwargs)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI-Studio-v88\App\python_embeded\Lib\site-packages\griptape\drivers\prompt\openai_
                             chat_prompt_driver.py", line 105, in try_run
                                 result = self.client.chat.completions.create(**params)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI-Studio-v88\App\python_embeded\Lib\site-packages\openai\_utils\_utils.py", line
                             275, in wrapper
                                 return func(*args, **kwargs)
                                        ^^^^^^^^^^^^^^^^^^^^^
                               File
                             "D:\ComfyUI-Studio-v88\App\python_embeded\Lib\site-packages\openai\resources\chat\completio
                             ns.py", line 829, in create
                                 return self._post(
                                        ^^^^^^^^^^^
                               File "D:\ComfyUI-Studio-v88\App\python_embeded\Lib\site-packages\openai\_base_client.py",
                             line 1278, in post
                                 return cast(ResponseT, self.request(cast_to, opts, stream=stream,
                             stream_cls=stream_cls))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ^
                               File "D:\ComfyUI-Studio-v88\App\python_embeded\Lib\site-packages\openai\_base_client.py",
                             line 955, in request
                                 return self._request(
                                        ^^^^^^^^^^^^^^
                               File "D:\ComfyUI-Studio-v88\App\python_embeded\Lib\site-packages\openai\_base_client.py",
                             line 1059, in _request
                                 raise self._make_status_error_from_response(err.response) from None
                             openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4o` does not
                             exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None,
                             'code': 'model_not_found'}}
Prompt executed in 0.54 seconds

**Comment by shhlife** [comment]
It looks like you don't have access to gpt-4o.. That's the default that's used when creating an agent.

Using the Config nodes, you can specify different models for the agent.. can you try a different model?

![image](https://github.com/user-attachments/assets/a387b9d3-ffb0-4e0a-b6d3-888b15a01a4e)

Additionally, I believe you can go to platform.openai.com and see what models you have access to?

**Comment by shhlife** [comment]
No worries at all. :) If you want to use it w/out paying for OpenAI's api, you can also try using the ollama drivers - they can run locally on your machine.

https://www.youtube.com/watch?v=jIq_TL5xmX0&list=PLZRzNKLLiEyeK9VN-i53sUU1v5vBLl-nG&index=9&t=4s
