### ISSUE TITLE
ValueError: No user directories found

### ISSUE THREAD

**Issue by wilzamguerrero** [griptape-ai/ComfyUI-Griptape#202]
hi i have this problem when begin comfyui  um running this in kagle i clone the rep of comfyui griptape and i installed the requirements and         !pip install "griptape[all]" -U

Total VRAM 15095 MB, total RAM 32103 MB
pytorch version: 2.4.1+cu121
xformers version: 0.0.28.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 Tesla T4 : cudaMallocAsync

Traceback (most recent call last):
  File "/kaggle/working/SDZC/nodes.py", line 2092, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/kaggle/working/SDZC/custom_nodes/ComfyUI-Griptape/__init__.py", line 59, in <module>
    from .nodes.config.gtUILMStudioDriversConfig import gtUILMStudioDriversConfig
  File "/kaggle/working/SDZC/custom_nodes/ComfyUI-Griptape/nodes/config/gtUILMStudioDriversConfig.py", line 17, in <module>
    from ..drivers.gtUILMStudioChatPromptDriver import gtUILMStudioChatPromptDriver
  File "/kaggle/working/SDZC/custom_nodes/ComfyUI-Griptape/nodes/drivers/gtUILMStudioChatPromptDriver.py", line 4, in <module>
    from .gtUIOpenAiCompatibleChatPromptDriver import gtUIOpenAiCompatibleChatPromptDriver
  File "/kaggle/working/SDZC/custom_nodes/ComfyUI-Griptape/nodes/drivers/gtUIOpenAiCompatibleChatPromptDriver.py", line 3, in <module>
    from .gtUIOpenAiChatPromptDriver import gtUIOpenAiChatPromptDriver
  File "/kaggle/working/SDZC/custom_nodes/ComfyUI-Griptape/nodes/drivers/gtUIOpenAiChatPromptDriver.py", line 6, in <module>
    models = get_available_models("ChatModel")
  File "/kaggle/working/SDZC/custom_nodes/ComfyUI-Griptape/nodes/utils/openai_utils.py", line 34, in get_available_models
    settings = GriptapeSettings()
  File "/kaggle/working/SDZC/custom_nodes/ComfyUI-Griptape/py/griptape_settings.py", line 25, in __init__
    self.setup()
  File "/kaggle/working/SDZC/custom_nodes/ComfyUI-Griptape/py/griptape_settings.py", line 124, in setup
    self.get_settings_file()
  File "/kaggle/working/SDZC/custom_nodes/ComfyUI-Griptape/py/griptape_settings.py", line 41, in get_settings_file
    raise ValueError("No user directories found")
ValueError: No user directories found

Cannot import /kaggle/working/SDZC/custom_nodes/ComfyUI-Griptape module for custom nodes: No user directories found

**Comment by shhlife** [comment]
This is using Kaggle? How are you setting it up to run? It seems to be having trouble when it's trying to find the user directory.. do you have instructions on how you got ComfyUI working with Kaggle? If you can send me those, I can try and re-create.

**Comment by shhlife** [comment]
hmm.. are you able to reproduce the error?

**Comment by shhlife** [comment]
does Kagle not allow you to install via the comfyUI manager?

**Comment by shhlife** [comment]
Okay - do you have an example of how to get ComfyUI working in Kagle without Griptape? I'd be happy to follow a tutorial to get it up and running and see if I can re-create the issue.

**Comment by shhlife** [comment]
hmm -that example didn't work for me at all - it couldn't install anything. Basically stuck in this loop:

![image](https://github.com/user-attachments/assets/a3bb9429-723c-418e-9a8a-157edefe1414)

I'll see if I can remove the need for the user directories

**Comment by shhlife** [comment]
can you re-send that with indented code? you can wrap it in ``` :)

**Comment by shhlife** [comment]
I tried this:
```
update = False

import os

base_path = "/kaggle/working"
zzz_path = os.path.join(base_path, "zzz")

os.chdir(base_path)
!git clone --depth 1 https://github.com/comfyanonymous/ComfyUI.git zzz
os.chdir(zzz_path)

!pip uninstall torch torchvision torchaudio xformers -y
!pip install torch torchvision torchaudio xformers==0.0.28.post3 --extra-index-url https://download.pytorch.org/whl/cu121
!pip install -r requirements.txt
#!pip install --upgrade gguf
#!pip install bitsandbytes>=0.43.0
!mamba install openssh -y
!pip install PyOpenGL PyOpenGL_accelerate
!pip install groq
!pip install blend_modes
!pip install einops
!pip install pyngrok
!pip install fal_client
!pip install "griptape[all]" -U

from multiprocessing import Process

def run_app():
    cmd = f"python {zzz_path}/main.py --dont-print-server & ssh -o StrictHostKeyChecking=no -p 80 -R0:localhost:8188 a.pinggy.io > log.txt"
    get_ipython().system(cmd)

def print_url():
    time.sleep(2)
    found = False
    end_word = '.pinggy.link'
    with open('log.txt', 'r') as file:
        for line in file:
            start_index = line.find("http:")
            if start_index != -1:
                end_index = line.find(end_word, start_index)
            if end_index != -1:
                url = line[start_index:end_index + len(end_word)]
                print(f"{url}")
                found = True
    if not found:
        print_url()

p_app = Process(target=run_app)
p_url = Process(target=print_url)
p_app.start()
p_url.start()
p_app.join()
p_url.join()

!python main.py
```

but it seems to be failing here:

```
Cloning into 'zzz'...
fatal: unable to access 'https://github.com/comfyanonymous/ComfyUI.git/': Could not resolve host: github.com
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[5], line 10
      8 os.chdir(base_path)
      9 get_ipython().system('git clone --depth 1 https://github.com/comfyanonymous/ComfyUI.git zzz')
---> 10 os.chdir(zzz_path)
     12 get_ipython().system('pip uninstall torch torchvision torchaudio xformers -y')
     13 get_ipython().system('pip install torch torchvision torchaudio xformers==0.0.28.post3 --extra-index-url https://download.pytorch.org/whl/cu121')

FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/working/zzz'
```

**Comment by shhlife** [comment]
I just pushed a new release that will try and create the user directory if it doesn't exist - maybe that will resolve it?

**Comment by shhlife** [comment]
yeah, I don't know why I can't get it to work - but can you give the latest update a try and see if it solves your other problem?

**Comment by shhlife** [comment]
my pleasure - and always happy to add more to the nodes. what kind of utilities do you have in mind?

**Comment by shhlife** [comment]
discord is easy - or just create a ticket so we can track it. :) So basically a switch node that will take multiple inputs and then allow you to choose a specific one as an output?

I think I could do that pretty easily.. but in your mockup, you've got "groups" of switch nodes, right? so a model & two prompts? Not sure if I could make something like that..

but the first one, yeah - that'd be easy enough to do

**Comment by shhlife** [comment]
Something like this?

![image](https://github.com/user-attachments/assets/ba463893-71d5-4d50-948d-62451eff5565)

**Comment by shhlife** [comment]
here it is with configuration nodes instead.. two switches so you can see the difference 
![image](https://github.com/user-attachments/assets/469ab389-5c2e-4709-924a-05224ed5d1e9)

**Comment by shhlife** [comment]
ahh.. that's not super easy to do.. as far as I know we can't do dynamic output count. the outputs are defined in python. One thing I could do is a series of switch nodes.. one with one output, one with two, one with three, one with four.. then you would just choose which count you need.. and you just need to make sure you enter the right number of input groups..

that might work? a bit complicated to figure out, but not impossible

**Comment by shhlife** [comment]
Okay, I've added it as a feature request: #218 

:)

in the meantime, I did just publish the single-dimensional switch node in the latest update.

also, back to the topic of this issue - did the latest update fix the problem?

**Comment by shhlife** [comment]
okay, thank you! we'll keep trying to make it work the first time. :)
